apiVersion: v1
data:
  APP_ENV: production
  APP_LOG_LEVEL: debug
  app-config.yaml: |
    app:
      name: web
      featureX: true
      timeoutSeconds: 10
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"APP_ENV":"production","APP_LOG_LEVEL":"debug","app-config.yaml":"app:\n  name: web\n  featureX: true\n  timeoutSeconds: 10\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"name":"app-config","namespace":"default"}}
  creationTimestamp: "2025-08-12T03:44:40Z"
  name: app-config
  namespace: default
  resourceVersion: "829858"
  uid: 2d0b105f-bb56-48af-bc6c-c037eece47ee
