apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configMapGenerator:
  - name: nginx-default
    literals:
      - default.conf=server {
          listen 80 default_server;
          listen [::]:80 default_server;
          server_name _;
          root /usr/share/nginx/html;
          location = /healthz { return 200 "ok\n"; add_header Content-Type text/plain; }
          location / { try_files $uri $uri/ =404; }
        }
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: web
    patch: |
      - op: add
        path: /spec/replicas
        value: 3
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests: { cpu: "100m", memory: "128Mi" }
          limits:   { cpu: "500m", memory: "256Mi" }
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe
        value:
          httpGet: { path: /healthz, port: 80 }
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe
        value:
          httpGet: { path: /healthz, port: 80 }
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: nginx-default
          configMap:
            name: nginx-default
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: nginx-default
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - secretRef:
              name: app-secrets
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: postgres
    patch: |
      - op: add
        path: /spec/template/spec/securityContext
        value: { runAsUser: 999, runAsGroup: 999, fsGroup: 999 }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: PGDATA, value: /var/lib/postgresql/data/pgdata }

