name: CI Smoke

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/smoke.yml"

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print context
        run: |
          echo "Repo: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Actor: $GITHUB_ACTOR"
          echo "SHA: $GITHUB_SHA"
          date

      - name: List files
        run: |
          pwd
          ls -la

      - name: Make artifact
        run: |
          echo "hello from $GITHUB_SHA on $(date)" > run-info.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: run-info
          path: run-info.txt
